### ISSUE TITLE
Use GitHub OAuth

### ISSUE THREAD

**Issue by babeuloula** [babeuloula/github-pr-review#50]
Implement GitHub OAuth to use the application and store users' data and configuration with Doctrine2.

## TODO

- [ ] Implement GitHub OAuth
- [ ] Use Doctirne2 with Annotation
- [ ] Store users' data and configuration in database
- [ ] Install Symfony firewall and create two roles `ROLE_USER` and `IS_AUTHENTICATED_ANONYMOUSLY`
    - [ ] Create a route `/login` to redirect non logged users (`IS_AUTHENTICATED_ANONYMOUSLY`)
    - [ ] Create a route `/redirect` to redirect after oauth connection (`IS_AUTHENTICATED_ANONYMOUSLY`)
    - [ ] Redirect non logged users to `/login`
    - [ ] All routes need `ROLE_USER`
- [ ] Create a profile page to manage your own configuration
